[window]
opacity = 0.84
padding.x = 4
padding.y = 4

[font]
size = 14.0

[font.bold]
family = "IosevkaTerm NF"
style = "Bold"

[font.bold_italic]
family = "IosevkaTerm NF"
style = "Bold Italic"

[font.italic]
family = "IosevkaTerm NF"
style = "Italic"

[font.normal]
family = "IosevkaTerm NF"
style = "Regular"

[colors.primary]
background = '#fbf1c7'
foreground = '#3c3836'

[colors.normal]
black   = '#fbf1c7'
red     = '#cc241d'
green   = '#98971a'
yellow  = '#d79921'
blue    = '#458588'
magenta = '#b16286'
cyan    = '#689d6a'
white   = '#7c6f64'

[colors.bright]
black   = '#928374'
red     = '#9d0006'
green   = '#79740e'
yellow  = '#b57614'
blue    = '#076678'
magenta = '#8f3f71'
cyan    = '#427b58'
white   = '#3c3836'

